services:
  mysql:
    container_name: spring_web
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: "spring_web"
      MYSQL_ROOT_PASSWORD: "1234"
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"